kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  # SOURCE: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock

  # https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts
    - containerPath: /var/lib/rancher/k3s/storage
      hostPath: ${PWD}/storage
      # propagation: Bidirectional
      readOnly: false

    - containerPath: /var/log/kubernetes/audit
      hostPath: ${PWD}/audit
      # propagation: Bidirectional
      readOnly: false
- role: control-plane
  # SOURCE: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock

  # https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts
    - containerPath: /var/lib/rancher/k3s/storage
      hostPath: ${PWD}/storage
      # propagation: Bidirectional
      readOnly: false

    - containerPath: /var/log/kubernetes/audit
      hostPath: ${PWD}/audit
      # propagation: Bidirectional
      readOnly: false
- role: control-plane
  # SOURCE: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock

  # https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts
    - containerPath: /var/lib/rancher/k3s/storage
      hostPath: ${PWD}/storage
      # propagation: Bidirectional
      readOnly: false

    - containerPath: /var/log/kubernetes/audit
      hostPath: ${PWD}/audit
      # propagation: Bidirectional
      readOnly: false


  extraPortMappings:
  - containerPort: 8443
    hostPort: 8443
  - containerPort: 30346
    hostPort: 9443
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

- role: worker
- role: worker
- role: worker
